services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Investments.WebApi/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    networks:
      - app-network
  frontend:
    build:
      context: ./src/frontend/investment-simulator
    ports:
      - "4200:4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
